<?php
    $lang = [
        'KIRKOS SUBCITY WEREDA 02 VITAL EVENT REGISTRATION' => 'በቂ/ክ/ወ/02 የወሳኝ ኩነት አገልግሎት',
        'Kirkos Subcity Wereda 02 Vital Event Registration' => 'በቂ/ክ/ወ/02 የወሳኝ ኩነት አገልግሎት',
        'head' => 'የወረዳ 02 የወሳኝ ኩነት አገልግሎት',
        'Welcome' => 'እንኳን ወደ ቂርቆስ ክፍለ ከተማ አስተዳደር የወረዳ 02 የወሳኝ ኩነት አገልግሎት በደህና መጡ',
        'Home' => 'ዋና ገጽ',
        'Register your vital events with ease' => 'አስፈላጊ ክስተቶችዎን በቀላሉ ያስመዝግቡ',
        'TIME' => 'ቀን',
        'home' => 'ዋና ገጽ',
        'About' => 'ስለ እኛ',            
        'Payment Request' => 'የክፍያ ጥያቄ',
        'Contact' => 'ያግኙን',
        'Death Application Status' => 'የሞት ማመልከቻ ሁኔታ',
        'Death Application' => 'የሞት ማመልከቻ',
        'Death Applications' => 'የሞት ማመልከቻ',
        'Register Death Application' => 'የሞት ማመልከቻ ይመዝገቡ',
        'View Death Application' => 'የሞት ማመልከቻን ይመልከቱ',
        'help' => 'እርዳታ',
        'Login' => 'ግባ',
        'Login Pageee' => 'የመግቢያ ገጽ',
        'Username' => 'የተጠቃሚ ስም',
        'Password' => 'የይለፍ ቃል',
        'Back' => 'ተመለስ',
        'Logout' => "ውጣ",
        'Death Status' => 'የሞት ሁኔታ',
        //manager
        
        'This is your personalized manager page' => 'ይህ የእርስዎ የግል አስተዳዳሪ ገጽ ነው።',
        // view dicorce child number
        'Divorce States' => 'የፍቺ ሁኔታ',
        "Wife's Name" => "የሚስት ስም",
        "Husband's Name" => "የባል ስም",
        'My Divorce Application' => 'የእኔ የፍቺ ማመልከቻ',
        'Marriage Status' => 'የጋብቻ ሁኔታ',
        'My Marriage application' => 'የእኔ ጋብቻ ማመልከቻ',
        '2024 Admin Portal. All rights reserved' => "2025 አስተዳዳሪ ፖርታል. ሁሉም መብቶች የተጠበቁ ናቸው",
        'This is your personalized adminstrator page' => "ይህ የእርስዎ ግላዊነት የተላበሰ የአስተዳዳሪ ገጽ ነው",
        'Kebele Id Number/fayeda' => "የቀበሌ መታወቂያ ወይም ፋይዳ ልዩ ቁጥር",
        '2024 Kirkos Subcity wereda 02 Vital Event Registration System' => '2025 ቂርቆስ ክፍለ ከተማ አስተዳደር የወረዳ 02 የወሳኝ ኩነት አገልግሎት',
        //
        'My Appointment' => "የእኔ ቀጠሮ",
        'Appointment ID' => "የቀጠሮ ቁጥር",
        'Event Type' => "የክስተት አይነት",
        'Appointment Date' => "የቀጠሮ ቀን",
        'There are no scheduled appointments for you' => "ለእርስዎ ምንም የታቀዱ ቀጠሮዎች የሉም",
//
'Create Account' => "አካውንት ይፍጠሩ",
'User Type' => "የተጠቃሚ ዓይነት",
//
'2024 Child Portal' => "2025 የልጆች ፖርታል",
'ID' => "መለያ",
'Account Status' => "የአካውንት ሁኔታ",
'Vital Event Info' => "ወሳኝ የክስተት መረጃ",
'Applicant List' => "የአመልካቾች ዝርዝር",
'view' => "እይታ",
'Search' => "ፈልግ",
'Show All Applicants' => "ሁሉንም አመልካቾች አሳይ",
//
'User List' => "የተጠቃሚዎች ዝርዝር",
'Action' => "ድርጊት",
'Mother Name' => "የእናት ስም",
'Applicant Birth Requests' => "የአመልካች የልደት ጥያቄዎች",
'Reject' => "አትቀበል",
'Approve' => "አጽድቅ",
'Death Application Requests' => 'የሞት ማመልከቻ ጥያቄዎች',
        'Register births online and manage birth records securely' => 'ልደትን ባሉበት ቦታ ሆነው ያስመዝግቡ የልደት መዝገቦችን ደህንነቱ በተጠበቀ ሁኔታ ያስተዳድሩ።',
        'Births' => 'ልደቶች',
        'Marriages' => 'ጋብቻዎች',
        'Record marriages and maintain marriage certificates digitally' => 'ጋብቻን ይመዝግቡ እና የጋብቻ የምስክር ወረቀቶችን በዲጂታል መንገድ ያቆዩ',
        'Deaths' => 'ሞቶች',
        'Submit death certificates electronically for efficient processing' => 'ለቅልጥፍና ሂደት የሞት የምስክር ወረቀቶችን በኤሌክትሮኒክ መንገድ ያስገቡ',
        'Divorces' => 'ፍቺዎች',
        'Apply for divorces and manage divorce documents' => 'ለፍቺ ያመልክቱ እና የፍቺ ሰነዶችን ያስተዳድሩ',
        '2025 Kirkos Sub City wereda 02 Vital Event Registration System' => '2025 በቂርቆስ ክ/ከተማ ወረዳ 02 ወሳኝ ኩነት ምዝገባ ስርዓት',
        //anoutus
        'About Vital Event Registration' => 'ስለ ወሳኝ ኩነት ምዝገባ',

        'Our Services' => 'የእኛ አገልግሎቶች',
        'Our mission is' => 'የእኛ ተልእኮ እንከን የለሽ፣ ትክክለኛ እና ቀልጣፋ የወሳኝ ኩነት ምዝገባ መፍትሄዎችን ማቅረብ ነው፣ ይህም እያንዳንዱ የህይወት ምዕራፍ በትክክል መዝግቦ እና እውቅና መስጠቱን ማረጋገጥ ነው።',
        'Welcome to' => 'እንኳን ወደ ቂርቆስ ክ/ከተማ ወረዳ 02 የወሳኝ ኩነት ምዝገባ አገልግሎት ታማኝ አጋርዎ ሆኑ። ከ2008 E.C/2016 G.C ጀምሮ ለግለሰቦች፣ ቤተሰቦች እና ድርጅቶች የወሳኝ ኩነት ምዝገባ ሂደትን ለማቃለል ቆርጠናል',
        'Our Mission' => 'ተልዕኳችን',
        'At Vital Event' => 'በወሳኝ ኩነት ምዝገባ የደንበኞቻችንን የተለያዩ ፍላጎቶች ለማሟላት የተዘጋጁ ሁለገብ አገልግሎቶችን እናቀርባለን።',
        'Birth Registration' => 'የልደት ምዝገባ',
        'Marriage Registration' => 'የጋብቻ ምዝገባ',
        'Death Registration' => 'የሞት ምዝገባ',
        'Divorce Registration' => 'የፍቺ ምዝገባ',
        'Meet Our Team' => 'ቡድናችንን ያግኙ',
        'Role: Manager' => 'ሚና፡ ሥራ አስኪያጅ',
        'Role: CivilRregistrar' => 'ሚና፡- የሲቪል መዝጋቢ',
        'With over' => 'በወሳኝ ኩነት ምዝገባ ከ10 ዓመት በላይ ልምድ ያለው',
    // contactus Husband age
    'Our Location' => 'አድራሻችን',
    'Near AASTU' => 'ከደንበል ወደ መስቀል ፍላወር መንገድ ህብረት ባንክ ፊት ለፊት ቂርቆስ ክፍለ ከተማ አስተዳደር የወረዳ 02 የወሳኝ ኩነት አገልግሎት አ.አ ኢትዮጵያ',
    'Contact Details' => 'የእውቂያ ዝርዝሮች',
    'Phone' => 'ስልክ',
    'Email' => 'ኢሜይል',
    'Our Social Media Platform' => 'የማህበራዊ ሚዲያ መድረካችን',
    'Office Hours' => 'የሥራ ሰዓት',
    'Monday' => 'ከሰኞ - አርብ: ጠዋት 3:00  - ከሰአት 11:00 ',
    'Saturday' => 'ቅዳሜ - እሁድ: ዝግ ቀናት',
    'General Inquiries' => 'አጠቃላይ ጥያቄዎች',
    'For general' => 'ለአጠቃላይ ጥያቄዎች፣ እባክዎን በስራ ሰዓት እኛን ለማግኘት ነፃነት ይሰማዎ',
// daath page
'Register Death Form' => 'የሞት ቅጽ ይመዝገቡ',
'Deceased Kebele ID/fayeda Number' => 'የሟች ቀበሌ ወይም ፋይዳ መታወቂያ ቁጥር',
'Email(your)' => 'ኢሜል (የእርስዎ)',
'Viewer ID' => 'ተመልካች መለያ',
'Deceased Name' => 'የሟች ስም',
'Death Paper' => "የሞት ወረቀት",
'Deceased First Name' => 'የሟች የመጀመሪያ ስም',
'Deceased Middle Name' => 'የሟች የአባት ስም',
'Deceased Last Name' => 'የሟች የአያት ስም',
'Gender' => 'ጾታ',
"Nationality" => "ዜግነት",
'Birth date' => 'የልደት ቀን',
'Date of death' => 'የሞት ቀን',
'Place of Death' => 'የሞት ቦታ',
'Registration date' => 'የምዝገባ ቀን',
'Marital status' => 'የጋብቻ ሁኔታ',
'Number of child' => 'የልጅ ብዛት',
'Registrant' => "የተመዝጋቢው ስም (የእርስዎ ስም)",
'Father Name' => 'የአባት ስም',
'Relationship type' => 'ዝምድና',
'Upload Deceased' => "የሟች ህጋዊ ሰነዶችን እና መታወቂያን ይስቀሉ (ከህጋዊ ድርጅት)",
'I certify' => 'ከላይ ያለው መረጃ መጠናቀቁን እና ትክክል መሆኑን አረጋግጣለሁ። ቂርቆስ ክፍለ ከተማ አስተዳደር የወረዳ 02 የወሳኝ ኩነት አገልግሎት የወሳኝ ኩነት ምዝገባ ከላይ በተገለጸው የስም አጻጻፍ እንዲጠቀም ፈቅጃለሁ።',
'Back' => 'ተመለስ',
'All Divorce Requests' => 'ሁሉም የፍቺ ጥያቄዎች',
'Death_age' => 'የሞት_እድሜ',
    //birth registration form Nationality Gender
    'Register' => 'ይመዝገቡ',
    'Birth Paper from recognized legal or Religional organization' => 'የልደት ወረቀት ከታወቀ የህግ ወይም የሃይማኖት ድርጅት',
    "Father's Nationality" => "የአባት ዜግነት",
    "Mother's Nationality" => "የእናት ዜግነት",
    "Father's Last Name" => "የአባት የአያት ስም ",
    "Father's Middle Name" => "የአባት የአባት ስም ",
    "Father's First Name" => "የአባት የመጀመሪያ ስም ",
    "Mother's First Name" => "የእናት የመጀመሪያ ስም",
    "Mother's Middle Name" => "የእናት የአባት ስም",
    "Mother's Last Name" => "የእናት የአያት ስም",
    'Birth Registration Form' => 'የልደት ምዝገባ ቅጽ',
    'All Marriage Requests' => "ሁሉም የጋብቻ ጥያቄዎች",
    'Marriage Paper' => 'የጋብቻ ወረቀት',
    //divorce registration All Marriage Requests
    'Divorce Paper' => 'የፍቺ ወረቀት',
    'Divorce Paper (PDF)' => 'የፍቺ ወረቀት (ፒዲኤፍ)',
    'Place of divorce dissloved' => 'ፍቺው የተፈፀመበት ቦታ',
    'Divorce date' => ' የፍቺ ቀን ',
    "Husband's Nationality" => "የባል ዜግነት",
    "Wife's Nationality" => "የሚስት ዜግነት",
    "Wife's Last Name" => "የሚስት የአያት ስም",
    "Wife's Middle Name" => "የሚስት የአባት ስም",
    "Wife's First Name" => "የሚስት የመጀመሪያ ስም",
    "Husband's Last Name" => "የባል የአያት ስም",
    "Husband's Middle Name" => "የባል የአባት ስም",
    "Husband's First Name" => "የባል የመጀመሪያ ስም",
    'Place of Birth' => 'የትውልድ ቦታ',
    'Wife Birth date' => 'የሚስት የልደት ቀን',
    'Husband Birth date' => 'የባል የልደት ቀን',
    'Divorce Registertion Form' => 'የፍቺ ምዝገባ ቅጽ',
    'Male' => 'ወንድ',
    //print birth Grandfather Name Father Name Date of Birth
    'Download Certificate' => 'የምስክር ወረቀት አውርድ',
    'This certificate' => 'ይህ የምስክር ወረቀት የተሰጠው በኢ.ፌ.ዲ.ሪ. የወሳኝ ኩነት ምዝገባ ኤጀንሲ ደንብ መሰረት ነው።',
    'Grandfather Name' => 'የአያት ስም',
    'Name of Civil Registrar' => 'የሲቪል መዝጋቢ ስም',
    'Kebele' => 'ቀበሌ',
    'Zone' => 'ዞን',
    'Region' => 'ክልል',
    'Birth Identification Number' => 'የልደት መለያ ቁጥር',
    'Birth Certificate' => 'የልደት የምስክር ወረቀት',
    'Federal Democratic Republic of Ethiopia Vital Event Registration Agency' => 'የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ የወሳኝ ኩነት ምዝገባ ኤጀንሲ',
    'This is a temporary computer-generated certificate' => 'ይህ ጊዜያዊ በኮምፒውተር የተፈጠረ የምስክር ወረቀት ነው።',
    //print divorce husband name
    'wife age' => 'የሚስት ዕድሜ',
    'Husband age' => 'የባል ዕድሜ',
    'Death Identification Number' => 'የሞት መለያ ቁጥር',
    'Divorce Certificate' => 'የፍቺ የምስክር ወረቀት',
    'Region' => 'ክልል',
    'Account Upgrade Request' => 'የአካውንት ማሻሻያ ጥያቄ',
    //account requst
    'Keble ID/fayeda Photo' => 'የቀበሌ መታወቂያ ወይም የፋይዳ ፎቶ',
    'Applicant Account Request' => 'የአመልካች አካውንት ጥያቄ',
    'No new Request found' => 'ምንም አዲስ ጥያቄ አልተገኘም',
    'Reject applicant' => 'አመልካቹን ውድቅ ያድርጉ',
    'Approve applicant' => 'አመልካቹን አጽድቅ',
    //
    'Child Account Request' => "የልጅ አካውንት ጥያቄ",
'Birth Paper' => "የልደት ወረቀት",
'Father kebele id' => "የአባት ቀበሌ መታወቂያ",
    //print marriage
    'Marriage Certificate' => 'የጋብቻ የምስክር ወረቀት',
    'Marriage Identification Number' => 'የጋብቻ መለያ ቁጥር',
//feedback
'Feedback Form' => 'የግብረመልስ ቅጽ',
'Submit' => 'ላክ',
'Feedback Message' => 'የግብረመልስ መልዕክት',
'Reset' => 'ዳግም አስጀምር',
    //myapplication
    'Birth ID' => 'የልደት መለያ',
    'Name' => 'ስም',
    'Birth Status' => 'የልደት ሁኔታ',
    'Payment Status' => 'የክፍያ ሁኔታ',
    'More Details' => 'ተጨማሪ ዝርዝሮች',
    'My Birth Application' => 'የእኔ የልደት ማመልከቻ',
    'Mother Name' => 'የእናት ስም',
//send paymnet birth
'Send Payment Form' => 'የክፍያ ቅጽ ላክ',
'Check payment amounts' => 'የክፍያ መጠኖችን ያረጋግጡ',
'before making payment' => 'ክፍያ ከመፈጸምዎ በፊት',
'Payment URL' => 'የክፍያ አድራሻ',
'here' => 'እዚህ',
    //marriage registaer
    'Marriage Paper(from legal orgnization) (PDF)' => 'የጋብቻ ወረቀት (ከህጋዊ ድርጅት) (ፒዲኤፍ)',
    'Date of Marriage' => 'የጋብቻ ቀን',
    'Hasband Birth place' => 'የባል የትውልድ ቦታ',
    'Wife Birth Place' => 'የሚስት የትውልድ ቦታ',
    'Marriage Registartion Form' => 'የጋብቻ ምዝገባ ቅጽ',
    'Male' => 'ወንድ',
            //childsignup
            'Childd' => "የልጅ የልደት ወረቀት ከህጋዊ ድርጅት (ፒዲኤፍ ብቻ)",
            'Child Username' => 'የልጅ የተጠቃሚ ስም',
            'Child Grandfather name' => 'የልጅ የአያት ስም',
            'Child Father name' => 'የልጅ የአባት ስም',
            'Child Name' => 'የልጅ ስም',
         'Here you' => 'እዚህ ልጅዎን ማስመዝገብ የሚችሉት የቀበሌ መታወቂያ ካርድ የሌለውን ከ18 ዓመት በታች ለሆኑት ልደት ለመመዝገብ ብቻ ነው ',
         'children  Signup' => 'የልጆች ምዝገባ',
         'Male' => 'ወንድ',
// view dearh
'View Death Application' => "የሞት ማመልከቻን ይመልከቱ",
'Enter your viewer code' => "የተመልካችዎን ኮድ ያስገቡ",
'Enter the kebele id of the deceased person' => "የሟችውን ቀበሌ መታወቂያ ወይም ፋይዳ መለያ ያስገቡ",
//login page

'If you do not have an account' => 'የአካውንት ከሌልዎትs',
'sign up' => 'ይመዝገቡ',
'If you forget your password' => 'የይለፍ ቃልዎን ከረሱ',
'click here' => 'እዚህ ጠቅ ያድርጉ',
        // applicant signup
        'Applicant Signup' => 'የአመልካች መዝገብ',
        'First Name' => 'የመጀመሪያ ስም',
        'Middle Name' => 'መካከለኛ ስም',
        'Last Name' => 'የአያት ስም',
        'Phone number' => 'ስልክ ቁጥር',
        'Religion' => 'እምነት',
        'Scanned Kebele ID (PDF Only)' => 'የቀበሌ ወይም ፋይዳ መታወቂያ ስካን (ፒዲኤፍ ብቻ)',
        'I have an account' => 'አካውን አለኝ',
        'here you can change to pdf' => 'እዚህ ወደ ፒዲኤፍ ሊለውጡ ይችላሉ',
        'Make PDF' => 'ወደ ፒዲኤፍ ለውጥ',
        'signup' => 'መመዝገብ',
        'Female' => 'ሴት',
        'Male' => 'ወንድ',
        'Convert to PDF' => 'ወደ ፒዲኤፍ ለውጥ',
        //
        'Death Certificate' => 'የሞት የማረጋገጫ ወረቀት',
        'Death Identification Number' => 'የሞት መለያ ቁጥር',
        'country' => 'አገር',
        'Birth Registration Form' => 'የልደት ምዝገባ ፎርም',
       
         //manager page 
 
         'Database Backup' => 'የመረጃ ቋት ምትኬ',
         'Generate Report' => 'ሪፖርት ማመንጨት',
         
         'View Vital Event' => 'ወሳኝ ክስተት ይመልከቱ',
        
         'View Comments' => 'አስተያየቶችን ይመልከቱ',
   
   
   
         'Birth Report' => 'የልደት ሪፖርት',
         'Death Report' => 'የሞት ሪፖርት',
         'Divorce Report' => 'የፍቺ ሪፖርት',
         'Marriage Report' => "የጋብቻ ሪፖርት",
         'User Report' => 'የተጠቃሚ ሪፖርት',
         'Payment Info' => 'የክፍያ መረጃ',

        'Manage User' => 'ተጠቃሚን ማስተዳደር',
     
         

    //applicant page
    '2024 applicant Portal' => 'የ2024 አመልካች ፖርታል',
'This is your personalized applicant Page' => 'ይህ የእርስዎ ግላዊነት የተላበሰ የአመልካች ገጽ ነው',
'Welcomee' => 'እንኳን ደህና መጡ',

'Register vital Event' => 'አስፈላጊ ክስተት ይመዝግቡ',
'My application' => 'ማመልከቻዬ',
'Print certificate' => 'ሰርተፍኬት ያትሙ',

'Send payment' => 'ክፍያ ይላኩ',
'View appointment' => 'ቀጠሮ ይመልከቱ',

'Birth Application' => 'የልደት ማመልከቻ',
'Child Birth Application' => "የልጅ ልደት ማመልከቻ",
'Divorce Application' => 'የፍቺ ማመልከቻ',
'Marriage Application' => "የጋብቻ ማመልከቻ",
'Birth Certificate' => 'የልደት የምስክር ወረቀት',
'Divorce Certificate' => 'የፍቺ የምስክር ወረቀት',
'Marriage Certificate' => 'የጋብቻ የምስክር ወረቀት',
'Feedbacks' => 'ግብረመልሶች',
'Send Feedback' => 'ግብረመልስ ይላኩ',

'View Feedback' => 'ግብረመልስ ይመልከቱ',
'Birth Payment' => 'የልደት ክፍያ',
'Divorce Payment' => 'የፍቺ ክፍያ',
'Marriage Payment' =>"የጋብቻ ክፍያ",

'Change Password' => 'የይለፍ ቃል ይቀይሩ',

    //civil registarar page 
    'Account Request' => 'የአካውንት ጥያቄ',
'Vital Event Request' => 'አስፈላጊ የክስተት ጥያቄ',
'View Applicant' => 'አመልካች ይመልከቱ',
'Applicants Application' => 'የአመልካቾች ማመልከቻ',
'Comment' => 'አስተያየት',
'View feedback' => 'ግብረመልስ ይመልከቱ',
'Approve Payment' => 'ክፍያ ያጽድቁ',

'Child Account Request' => 'የልጅ አካውንት ጥያቄ',
'Account upgrade Request' => 'የአካውንት ማሻሻያ ጥያቄ',
'Death Application' => 'የሞት ማመልከቻ',
'Send Comment' => 'አስተያየት ይላኩ',
'Manger Response' => 'የአስተዳዳሪ ምላሽ',
'Death payment' => 'የሞት ክፍያ',
'Give Appointment' => 'ቀጠሮ ይስጡ',

    //child page 
    'Child Birth Application' => 'የልጅ ልደት ማመልከቻ',
'My application' => 'ማመልከቻዬ',
'Print Birth certificate' => 'የልደት የምስክር ወረቀት ያትሙ',
'Send payment' => 'ክፍያ ይላኩ',
'Upgrade to Applicant' => 'ወደ አመልካችነት ያድጉ',
    //admin 
    'Create account' => 'አካውንት ይፍጠሩ',
'View applicant account' => 'የአመልካች አካውንት ይመልከቱ',
'View User account' => 'የተጠቃሚ አካውንት ይመልከቱ',
    //death page
   'View Death Application' => "የሞት ማመልከቻን ይመልከቱ",
'Print Death Certificate' => "የሞት የምስክር ወረቀት ያትሙ",

'View appointment' => 'ቀጠሮ ይመልከቱ',


'Here you can' => 'እዚህ ጋር ትክክለኛ የቀበሌ መታወቂያ ወይም ፋይዳ ካለዎት አካውንትዎን ማሳደግ ይችላሉ',
'child upgrade page' => 'የልጅ ማሻሻያ ገጽ',
'Upgrade' => 'ማሻሻል',
'Kebele ID (PDF Only)' => 'የቀበሌ ወይም ፋይዳ መታወቂያ (ፒዲኤፍ ብቻ)',



    //payment info Account Status
    'Vital Event Payment Information' => 'የወሳኝ ክስተት ክፍያ መረጃ',
'Welcome to our vital event' => 'ወደ ወሳኝ ክስተት ክፍያ ገጻችን እንኳን በደህና መጡ። ከዚህ በታች እንደ ልደት፣ ሞት፣ ፍቺ እና ጋብቻ ላሉ የተለያዩ ወሳኝ ክስተቶች የክፍያ መረጃ ያገኛሉ',
'Please use the account' => 'ለወሳኝ ክስተት ምዝገባ ክፍያዎችን ለመፈጸም ከላይ የቀረበውን የሂሳብ ቁጥር ይጠቀሙ',
'Our Account: CBE 1000096883084' => 'የእኛ አካውንት: CBE 1000096883084',
'Registration' => 'ምዝገባ',
'Event Type' => 'የክስተት አይነት',
'Payment Amount' => 'የክፍያ መጠን',
'After making the payment, please send us the payment confirmation through our system using the provided payment link' => 'ክፍያውን ከፈጸሙ በኋላ፣ እባክዎን በተሰጠው የክፍያ ማገናኛ በኩል በስርዓታችን የክፍያ ማረጋገጫውን ይላኩልን',
'Birr' => 'ብር',
    //approve
    'Birth Appointment' => 'የልደት ቀጠሮ',
'Death Appointment' => 'የሞት ቀጠሮ',
'Divorce Appointment' => 'የፍቺ ቀጠሮ',
'Marriage Appointment' => 'የጋብቻ ቀጠሮ',
'All Appointments' => 'ሁሉም ቀጠሮዎች',


    
    'Appointment List' => 'የቀጠሮ ዝርዝር',
'No Ready unscheduled Birth certificate found' => 'ዝግጁ ያልሆነ ያልተያዘ የልደት የምስክር ወረቀት አልተገኘም',
'Make Appointment' => 'ቀጠሮ ይስጡ',
'No Ready unscheduled  Death certificate found' => 'ዝግጁ ያልሆነ ያልተያዘ የሞት የምስክር ወረቀት አልተገኘም',
'Death ID' => "የሞት መለያ",
'Death ID' => 'የሞት መለያ',
'No Ready unscheduled  Divorce certificate found' => 'ዝግጁ ያልሆነ ያልተያዘ የፍቺ የምስክር ወረቀት አልተገኘም',
'Divorce ID' => 'የፍቺ መለያ',
'Marriage ID' => 'የጋብቻ መለያ',
'No Ready unscheduled  marriage certificate found' => 'ዝግጁ ያልሆነ ያልተያዘ የጋብቻ የምስክር ወረቀት አልተገኘም',

'Comment Form' => 'የአስተያየት ቅጽ',
'Comment Message' => 'የአስተያየት መልዕክት',
'This is your personalized children Page' => "ይህ የእርስዎ ግላዊነት የተላበሰ የልጆች ገጽ ነው",
'This is your personalized civil Registrar page' => 'ይህ የእርስዎ ግላዊነት የተላበሰ የሲቪል ሬጅስትራር ገጽ ነው',
    
    // Birth report
    'Birth Report' => 'የልደት ሪፖርት',
'Total Number of Births' => 'ጠቅላላ የልደት ብዛት',
'Total Number of Approved Registrations' => 'ጠቅላላ የጸደቁ ምዝገባዎች ብዛት',
'Total Number of Pending Registrations' => 'ጠቅላላ በመጠባበቅ ላይ ያሉ ምዝገባዎች ብዛት',
'Total Number of Certified Users' => 'ጠቅላላ የተረጋገጡ ተጠቃሚዎች ብዛት',
'Total Number of Unpaid Registrations' => 'ጠቅላላ ያልተከፈለባቸው ምዝገባዎች ብዛት',
'Total Number of Paid Registrations' => 'ጠቅላላ የተከፈለባቸው ምዝገባዎች ብዛት',
    //Death Report
    'Death Report' => 'የሞት ሪፖርት',
'Total Number of Deaths' => 'ጠቅላላ የሞት ብዛት',
'Total Number of Pending Deaths' => 'ጠቅላላ በመጠባበቅ ላይ ያሉ የሞት ምዝገባዎች ብዛት',
'Total Number of Approved Deaths' => 'ጠቅላላ የጸደቁ የሞት ምዝገባዎች ብዛት',
'Total Number of Paid Deaths' => 'ጠቅላላ የተከፈለባቸው የሞት ምዝገባዎች ብዛት',
'Total Number of Unpaid Deaths' => 'ጠቅላላ ያልተከፈለባቸው የሞት ምዝገባዎች ብዛት',
'Total Number of Certified Deaths' => 'ጠቅላላ የተረጋገጡ የሞት የምስክር ወረቀቶች ብዛት',

//Divorce Report
'Divorce Report' => 'የፍቺ ሪፖርት',
'DIVORCE REGISTRATION SYSTEM' => 'የፍቺ ምዝገባ ስርዓት',
'Total Number of Divorces' => 'ጠቅላላ የፍቺዎች ብዛት',
'Total Number of Pending Divorces' => 'ጠቅላላ በመጠባበቅ ላይ ያሉ የፍቺ ምዝገባዎች ብዛት',
'Total Number of Approved Divorces' => 'ጠቅላላ የጸደቁ የፍቺ ምዝገባዎች ብዛት',
'Total Number of Paid Divorces' => 'ጠቅላላ የተከፈለባቸው የፍቺ ምዝገባዎች ብዛት',
'Total Number of Unpaid Divorces' => 'ጠቅላላ ያልተከፈለባቸው የፍቺ ምዝገባዎች ብዛት',
'Total Number of Certified Divorces' => 'ጠቅላላ የተረጋገጡ የፍቺ የምስክር ወረቀቶች ብዛት',
//Marriage Registration System
'Marriage Registration System' => 'የጋብቻ ምዝገባ ስርዓት',
'Total Number of Marriages' => 'ጠቅላላ የጋብቻዎች ብዛት',
'Total Number of Pending Marriages' => 'ጠቅላላ በመጠባበቅ ላይ ያሉ የጋብቻ ምዝገባዎች ብዛት',
'Total Number of Approved Marriages' => 'ጠቅላላ የጸደቁ የጋብቻ ምዝገባዎች ብዛት',
'Total Number of Paid Marriages' => 'ጠቅላላ የተከፈለባቸው የጋብቻ ምዝገባዎች ብዛት',
'Total Number of Unpaid Marriages' => 'ጠቅላላ ያልተከፈለባቸው የጋብቻ ምዝገባዎች ብዛት',
'Total Number of Certified Marriages' => 'ጠቅላላ የተረጋገጡ የጋብቻ የምስክር ወረቀቶች ብዛት',

//User Report
'User Report' => 'የተጠቃሚ ሪፖርት',
'Total Number of Users' => 'ጠቅላላ የተጠቃሚዎች ብዛት',
'Total Number of Applicants' => 'ጠቅላላ የአመልካቾች ብዛት',
'Total Number of Children' => 'ጠቅላላ የህጻናት ብዛት',
'Total Number of Admins' => 'ጠቅላላ የአስተዳዳሪዎች ብዛት',
'Total Number of Managers' => 'ጠቅላላ የአስተዳዳሪዎች ብዛት',
'Total Number of Civil Registrars' => 'ጠቅላላ የሲቪል ሬጅስትራሮች ብዛት',

//View Applicant
'View Applicant' => 'አመልካች ይመልከቱ',
'ALL APPLICANTS' => 'ሁሉም አመልካቾች',
'Return to All List' => 'ወደ ሁሉም ዝርዝር ይመለሱ',
'Id' => 'መለያ',
'Full Name' => 'ሙሉ ስም',

'Email' => 'ኢሜል',
'Phone' => 'ስልክ',
'Status' => 'ሁኔታ',
'Action' => 'እርምጃ',
    
    
    
    ]
?>