<?php 
    $lang = [
        'KIRKOS SUBCITY WEREDA 02 VITAL EVENT REGISTRATION' => 'KIRKOS SUBCITY WEREDA 02 VITAL EVENT REGISTRATION',
        'head' => 'KIRKOS SUBCITY WEREDA 02 VITAL EVENT REGISTRATION',
        'Welcome' => 'Welcome to Kirkos Subcity wereda 02 Vital Event Registration System',
        'Home' => 'Home',
        'Register your vital events with ease' => 'Register your vital events with ease',
        'TIME' => 'Date',
        'home' => 'Home',
        'About' => 'About',
        'Payment Request' => 'Payment Request',
        'Contact' => 'Contact',
        'Death Application Status' => 'Death Application Status',
        'Death Applications' => 'Death Application',
        'Register Death Application' => 'Register Death Application',
        'View Death Application' => 'View Death Application',
        'help' => 'እርዳታ',
        'Login' => 'Login',
        'Logout' => "Logout",
        'Death Status' => 'Death Status',
        '2024 Kirkos Subcity wereda 02 Vital Event Registration System' => '2025 Kirkos Subcity wereda 02 Vital Event Registration System',
        //manager
        
        'This is your personalized manager page' => 'This is your personalized manager page',

        // view dicorce child number
        
        'Divorce States' => 'Divorce States',
        "Wife's Name" => "Wife's Name",
        "Husband's Name" => "Husband's Name",
        'My Divorce Application' => 'My Divorce Application',
        'Marriage Status' => 'Marriage Status',
        'My Marriage application' => 'My Marriage application',
        '2025 Admin Portal. All rights reserved' => "2025 Admin Portal. All rights reserved",
        'This is your personalized adminstrator page' => "This is your personalized administrator page",
        'Kebele Id Number/fayeda' => "Kebele Id Number/fayeda",
       //
       'My Appointment' => "My Appointment",
       'Appointment ID' => "Appointment ID",
       'Event Type' => "Event Type",
       'Appointment Date' => "Appointment Date",
       'There are no scheduled appointments for you' => "There are no scheduled appointments for you",
//
'Create Account' => "Create Account",
'User Type' => "User Type",
//
'2024 Child Portal' => "2024 Child Portal",
'ID' => "ID",
'Account Status' => "Account Status",
'Vital Event Info' => "Vital Event Info",
'Applicant List' => "Applicant List",
'view' => "view",
'Search' => "Search",
'Show All Applicants' => "Show All Applicants",
//
'User List' => "User List",
'Action' => "Action",
'Mother Name' => "Mother Name",
'Applicant Birth Requests' => "Applicant Birth Requests",
'Reject' => "Reject",
'Approve' => "Approve",
'Death Application Requests' => 'Death Application Requests',
        'Register births online and manage birth records securely' => 'Register births online and manage birth records securely.',
        'Births' => 'Births',
        'Marriages' => 'Marriages',
        'Record marriages and maintain marriage certificates digitally' => 'Record marriages and maintain marriage certificates digitally',
        'Deaths' => 'Deaths',
        'Submit death certificates electronically for efficient processing' => 'Submit death certificates electronically for efficient processing',
        'Divorces' => 'Divorces',
        'Apply for divorces and manage divorce documents' => 'Apply for divorces and manage divorce documents',
        '2025 Kirkos Sub City wereda 02 Vital Event Registration System' => '2025 Kirkos Sub City wereda 02 Vital Event Registration System',
       //anoutus
       'About Vital Event Registration' => 'About Vital Event Registration',
      
       'Our Services' => 'Our Services',
       'Our mission is' => 'Our mission is to provide seamless, accurate, and efficient vital event registration solutions, ensuring that every milestone in life is properly documented and recognized',
       'Welcome to' => 'Welcome to Kirkos Subcity wereda 02 Vital Event Registration, your trusted partner for vital event registration services. Since 2008 E.C/2016 G.C, We have been dedicated to simplifying the vital event registration process for individuals, families, and organizations',
       'Our Mission' => 'Our Mission',
       'At Vital Event' => 'At Vital Event Registration, we offer a comprehensive range of services tailored to meet the diverse needs of our clients',
       'Birth Registration' => 'Birth Registration',
       'Marriage Registration' => 'Marriage Registration',
       'Death Registration' => 'Death Registration',
       'Divorce Registration' => 'Divorce Registration',
       'Meet Our Team' => 'Meet Our Team',
       'Role: Manager' => 'Role: Manager',
       'Role: CivilRregistrar' => 'Role: Civil Registrar',
       'With over' => 'With Over 10 years of experience in vital event registration',
    // contactus Husband age
    'Our Location' => 'Our Location',
    'Near AASTU' => 'Near AASTU University and CEB Bank Kilinto, Wereda 09, Ethiopia',
    'Contact Details' => 'Contact Details',
    'Phone' => 'Phone',
    'Email' => 'Email',
    'Our Social Media Platform' => 'Our Social Media Platform',
    'Office Hours' => 'Office Hours',
    'Monday' => 'Monday - Friday: 9:00 AM - 5:00 PM',
    'Saturday' => 'Saturday - Sunday: Closed',
    'General Inquiries' => 'General Inquiries',
    'For general' => 'For general inquiries, please feel free to contact us during office hours',
// daath page
'Register Death Form' => 'Register Death Form',
'Deceased Kebele ID/fayeda Number' => 'Deceased Kebele ID/fayeda Number',
'Email(your)' => 'Email(your)',
'Viewer ID' => 'Viewer ID',
'Deceased Name' => 'Deceased Name',
'Death Paper' => "Death Paper",
'Deceased First Name' => 'Deceased First Name',
'Deceased Middle Name' => 'Deceased Middle Name',
'Deceased Last Name' => 'Deceased Last Name',
'Gender' => 'Gender',
'Nationality' => 'Nationality',
'Birth date' => 'Birth date',
'Date of death' => 'Date of death',
'Place of Death' => 'Place of Death',
'Registration date' => 'Registration date',
'Marital status' => 'Marital status',
'Number of child' => 'Number of child',
'Registrant' => "Registrant's Name(your name)",
'Father Name' => 'Father Name',
'Relationship type' => 'Relationship',
'Upload Deceased' => "Upload Deceased's Legal Documents and Identification(from legal organization)",
'I certify' => 'I certify that the above information is completed and correct. I authorize the ganda chefee kebele vital event registration  to use the name spelling provided above',
'Back' => 'Back',
'All Divorce Requests' => 'All Divorce Requests',
'Death_age' => 'Death_age',
    //birth registration form Nationality Gender
    'Register' => 'Register',
    'Birth Paper from recognized legal or Religional organization' => 'Birth Paper from recognized legal or Religional organization',
    "Father's Nationality" => "Father's Nationality",
    "Mother's Nationality" => "Mother's Nationality",
    "Father's Last Name" => "Father's Last Name",
    "Father's Middle Name" => "Father's Middle Name",
    "Father's First Name" => "Father's First Name",
    "Mother's First Name" => "Mother's First Name",
    "Mother's Middle Name" => "Mother's Middle Name",
    "Mother's Last Name" => "Mother's Last Name",
    'Birth Registration Form' => 'Birth Registration Form',
    'All Marriage Requests' => "All Marriage Requests",
    'Marriage Paper' => 'Marriage Paper',
    //divorce registration All Marriage Requests
    'Divorce Paper' => 'Divorce Paper',
    'Divorce Paper (PDF)' => 'Divorce Paper (PDF)',
    'Place of divorce dissloved' => 'Place of divorce dissolved',
    'Divorce date' => ' Date of Divorce ',
    "Husband's Nationality" => "Husband's Nationality",
    "Wife's Nationality" => "Wife's Nationality",
    "Wife's Last Name" => "Wife's Last Name",
    "Wife's Middle Name" => "Wife's Middle Name",
    "Wife's First Name" => "Wife's First Name",
    "Husband's Last Name" => "Husband's Last Name",
    "Husband's Middle Name" => "Husband's Middle Name",
    "Husband's First Name" => "Husband's First Name",
    'Place of Birth' => 'Place of Birth',
    'Wife Birth date' => 'Wife Birth date',
    'Husband Birth date' => 'Husband Birth date',
    'Divorce Registertion Form' => 'Divorce Registertion Form',
    'Male' => 'Dhiira',
    //print birth Grandfather Name Father Name Date of Birth
    'Download Certificate' => 'Download Certificate',
    'This certificate' => 'This certificate is issued in accordance with the regulations of the F.D.R.E vital event registration agency',
    'Grandfather Name' => 'Grandfather Name',
    'Name of Civil Registrar' => 'Name of Civil Registrar',
    'Kebele' => 'Kebele',
    'Zone' => 'Zone',
    'Region' => 'Region',
    'Birth Identification Number' => 'Birth Identification Number',
    'Birth Certificate' => 'Birth Certificate',
    'Federal Democratic Republic of Ethiopia Vital Event Registration Agency' => 'Federal Democratic Republic of Ethiopia Vital Event Registration Agency',
    'This is a temporary computer-generated certificate' => 'This is a temporary computer-generated certificate',
    //print divorce husband name
    'wife age' => 'wife age',
    'Husband age' => 'Death country ',
    'Death Identification Number' => 'Divorce Identification Number',
    'Divorce Certificate' => 'Divorce Certificate',
    'Region' => 'Region',
    'Account Upgrade Request' => 'Account Upgrade Request',
    //account requst
    'Keble ID/fayeda Photo' => 'Keble ID/fayeda Photo',
    'Applicant Account Request' => 'Applicant Account Request',
    'No new Request found' => 'No new Request found',
    'Reject applicant' => 'Reject applicant',
    'Approve applicant' => 'Approve applicant',
    //
    'Child Account Request' => "Child Account Request",
'Birth Paper' => "Birth Paper",
'Father kebele id' => "Father kebele id",
    //print marriage
    'Marriage Certificate' => 'Marriage Certificate',
    'Marriage Identification Number' => 'Marriage Identification Number',
//feedback
'Feedback Form' => 'Feedback Form',
'Submit' => 'Submit',
'Feedback Message' => 'Feedback Message',
'Reset' => 'Reset',
    //myapplication
    'Birth ID' => 'Birth ID',
    'Name' => 'Name',
    'Birth Status' => 'Birth Status',
    'Payment Status' => 'Payment Status',
    'More Details' => 'More Details',
    'My Birth Application' => 'My Birth Application',
    'Mother Name' => 'Mother Name',
//send paymnet birth
'Send Payment Form' => 'Send Payment Form',
'Check payment amounts' => 'Check payment amounts',
'before making payment' => 'before making payment',
'Payment URL' => 'Payment URL',
'here' => 'here',
    //marriage registaer
    'Marriage Paper(from legal orgnization) (PDF)' => 'Marriage Paper(from legal orgnization) (PDF)',
    'Date of Marriage' => 'Date of Marriage',
    'Hasband Birth place' => 'Husband Birth place',
    'Wife Birth Place' => 'Wife Birth Place',
    'Marriage Registartion Form' => 'Marriage Registration Form',
    'Male' => 'Dhiira',
         //childsignup 
         'Childd' => "Child's Birth Paper from legal organization(PDF Only)",
         'Child Username' => 'Child Username',
         'Child Grandfather name' => 'Child Grandfather name',
         'Child Father name' => 'Child Father name',
         'Child Name' => 'Child Name',
         'Here you' => 'Here you can register your child only for registering birth for under 18 and have no kebele ID card',
         'children  Signup' => 'children  Signup',
         'Male' => 'Dhiira',
// view dearh
'View Death Application' => 'View Death Application',
'Enter your viewer code' => 'Enter your viewer code',
'Enter the kebele id of the deceased person' => 'Enter the kebele id of the deceased person',
//login page
'Login Pageee' => 'Login Page',
'Username' => 'Username',
'Password' => 'Password',
'If you do not have an account' => 'If you do not have an account',
'sign up' => 'Sign up',
'If you forget your password' => 'If you forget your password',
'click here' => 'click here',
        // applicant signup
        'Applicant Signup' => 'Applicant Signup',
        'First Name' => 'First Name',
        'Middle Name' => 'Middle Name',
        'Last Name' => 'Last Name',
        'Phone number' => 'Phone number',
        'Religion' => 'Religion',
        'Kebele Id Number' => 'Kebele Id Number',
        'Scanned Kebele ID (PDF Only)' => 'Scanned Kebele ID (PDF Only)',
        'I have an account' => 'I have an account',
        'here you can change to pdf' => 'here you can change to pdf',
        'Make PDF' => 'Make PDF',
        'signup' => 'signup',
        'Female' => 'Female',
        'Male' => 'Male',
        'Convert to PDF' => 'Convert to PDF',
        //
        'Death Certificate' => 'Death Certificate',
        'Death Identification Number' => 'Death Identification Number',
        'country' => 'country',
        'Birth Registration Form' => 'Birth Registration Form',
        'Username' => 'Username',
         //manager page 
 
         'Database Backup' => 'Database Backup',
         'Generate Report' => 'Generate Report',
         
         'View Vital Event' => 'Taatee Barbaachisaa Ilaali',
        
         'View Comments' => 'View Comments',
   
   
   
         'Birth Report' => 'Birth Report',
         'Death Report' => 'Death Report',
         'Divorce Report' => 'Divorce Report',
         'Marriage Report' => "Marriage Report",
         'User Report' => 'User Report',
         'Payment Info' => 'Payment Information',
         
         'Manage User' => 'Manage User',
     
         

    //applicant page
    '2024 applicant Portal' => '2024 applicant Portal',
    'This is your personalized applicant Page' => 'This is your personalized applicant Page',
    'Welcomee' => 'Welcome',
  
    'Register vital Event' => 'Register vital Event',
    'My application' => 'My application',
    'Print certificate' => 'Print certificate',
   
    'Send payment' => 'Send payment',
    'View appointment' => 'View appointment',

    'Birth Application' => 'Birth Application',
    'Child Birth Application' => "Child Birth Application",
    'Divorce Application' => 'Divorce Application',
    'Marriage Application' => "Marriage Application",
    'Birth Certificate' => 'Birth Certificate',
    'Divorce Certificate' => 'Divorce Certificate',
    'Marriage Certificate' => 'Marriage Certificate',
    'Feedbacks' => 'Feedbacks',
    'Send Feedback' => 'Send Feedback',

    'View Feedback' => 'View Feedback',
    'Birth Payment' => 'Birth Payment',
    'Divorce Payment' => 'Divorce Payment',
    'Marriage Payment' =>"Marriage Payment",

    'Change Password' => 'Change Password',

    //civil registarar page 
    'Account Request' => 'Account Request',
'Vital Event Request' => 'Vital Event Request',
'View Applicant' => 'View Applicant',
'Applicants Application' => 'Applicants Application',
'Comment' => 'Comment',
'View feedback' => 'View feedback',
'Approve Payment' => 'Approve payment',

'Child Account Request' => 'Child Account Request',
'Account upgrade Request' => 'Account upgrade Request',
'Death Application' => 'Death Application',
'Send Comment' => 'Send Comment',
'Manger Response' => 'Manager Response',
'Death payment' => 'Death payment',
'Give Appointment' => 'Give Appointment',

    //child page 
    'Child Birth Application' => 'Child Birth Application',
    'My application' => 'My application',
    'Print Birth certificate' => 'Print Birth certificate',
    'Send payment' => 'Send payment',
    'Upgrade to Applicant' => 'Upgrade to Applicant',
    //admin 
    'Create account' => 'Create account',
    'View applicant account' => 'View applicant account',
    'View User account' => 'View User account',
    //death page
    'View Death Application' => "View Death Application",
    'Print Death Certificate' => "Print Death Certificate",
    
    'View appointment' => 'View appointment',


    'Here you can' => 'Here you can upgrade your account if you have a valid Ganda Chefee Kebele ID',
    'child upgrade page' => 'child upgrade page',
    'Upgrade' => 'Upgrade',
    'Kebele ID (PDF Only)' => 'ID Kebele (PDF Qofa)',



    //payment info Account Status
    'Vital Event Payment Information' => 'Vital Event Payment Information',
    'Welcome to our vital event' => 'Welcome to our vital event payment page. Below, you will find the payment information for various vital events such as birth, death, divorce, and marriage',
    'Please use the account' => 'Please use the account number provided above to make payments for vital event registrations',
    'Our Account: CBE 1000096883084' => 'Our Account: CBE 1000096883084',
    'Registration' => 'Registration',
    'Event Type' => 'Event Type',
    'Payment Amount' => 'Payment Amount',
    'After making the payment, please send us the payment confirmation through our system using the provided payment link' => 'After making the payment, please send us the payment confirmation through our system using the provided payment link',
    'Birr' => 'Birr',
    //approve
    'Birth Appointment' => 'Birth Appointment',
    'Death Appointment' => 'Death Appointment',
    'Divorce Appointment' => 'Divorce Appointment',
    'Marriage Appointment' => 'Marriage Appointment',
    'All Appointments' => 'All Appointments',


    
    'Appointment List' => 'Appointment List',
    'No Ready unscheduled Birth certificate found' => 'No Ready unscheduled Birth certificate found',
    'Make Appointment' => 'Give Appointment',
    'No Ready unscheduled  Death certificate found' => 'No Ready unscheduled  Death certificate found',
    'Death ID' => "ID Du'aa",
    'Death ID' => 'Death ID',
    'No Ready unscheduled  Divorce certificate found' => 'No Ready unscheduled  Divorce certificate found',
    'Divorce ID' => 'Divorce ID',
    'Marriage ID' => 'Marriage ID',
    'No Ready unscheduled  marriage certificate found' => 'No Ready unscheduled  marriage certificate found',
   
    'Comment Form' => 'Comment Form',
    'Comment Message' => 'Comment Message',
    'This is your personalized children Page' => "This is your personalized children Page",
    'This is your personalized civil Registrar page' => 'This is your personalized civil Registrar page',
    
    // Birth report
    'Birth Report' => 'Birth Report',
    'Total Number of Births' => 'Total Number of Births',
    'Total Number of Approved Registrations' => 'Total Number of Approved Registrations',
    'Total Number of Pending Registrations' => 'Total Number of Pending Registrations',
    'Total Number of Certified Users' => 'Total Number of Certified Users',
    'Total Number of Unpaid Registrations' => 'Total Number of Unpaid Registrations',
    'Total Number of Paid Registrations' => 'Total Number of Paid Registrations',

    //Death Report
    'Death Report' => 'Death Report',
    'Total Number of Deaths' => 'Total Number of Deaths',
    'Total Number of Pending Deaths' => 'Total Number of Pending Deaths',
    'Total Number of Approved Deaths' => 'Total Number of Approved Deaths',
    'Total Number of Paid Deaths' => 'Total Number of Paid Deaths',
    'Total Number of Unpaid Deaths' => 'Total Number of Unpaid Deaths',
    'Total Number of Certified Deaths' => 'Total Number of Certified Deaths',

//Divorce Report
'Divorce Report' => 'Divorce Report',
'DIVORCE REGISTRATION SYSTEM' => 'DIVORCE REGISTRATION SYSTEM',
'Total Number of Divorces' => 'Total Number of Divorces',
'Total Number of Pending Divorces' => 'Total Number of Pending Divorces',
'Total Number of Approved Divorces' => 'Total Number of Approved Divorces',
'Total Number of Paid Divorces' => 'Total Number of Paid Divorces',
'Total Number of Unpaid Divorces' => 'Total Number of Unpaid Divorces',
'Total Number of Certified Divorces' => 'Total Number of Certified Divorces',

//Marriage Registration System
'Marriage Registration System' => 'Marriage Registration System',
'Total Number of Marriages' => 'Total Number of Marriages',
'Total Number of Pending Marriages' => 'Total Number of Pending Marriagest',
'Total Number of Approved Marriages' => 'Total Number of Approved Marriages',
'Total Number of Paid Marriages' => 'Total Number of Paid Marriages',
'Total Number of Unpaid Marriages' => 'Total Number of Unpaid Marriages',
'Total Number of Certified Marriages' => 'Total Number of Certified Marriages',

//User Report
'User Report' => 'User Report',
'Total Number of Users' => 'Total Number of Users',
'Total Number of Applicants' => 'Total Number of Applicants',
'Total Number of Children' => 'Total Number of Children',
'Total Number of Admins' => 'Total Number of Admins',
'Total Number of Managers' => 'Total Number of Managers',
'Total Number of Civil Registrars' => 'Total Number of Civil Registrars',

//View Applicant
'View Applicant' => 'View Applicant',
'ALL APPLICANTS' => 'ALL APPLICANTS',
'Return to All List' => 'Return to All List',
'Id' => 'Id',
'Full Name' => 'Full Name',
'Username' => 'Username',
'Email' => 'Email',
'Phone' => 'Phone',
'Status' => 'Status',
'Action' => 'Action',
    
    
    
    ]
?>